// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Tyok2vPh4qjXAnAnIzEkRCNHiiy6kiQ',
    appId: '1:944689820051:web:19dda9907b35ac8222f866',
    messagingSenderId: '944689820051',
    projectId: 'cook-d9323',
    authDomain: 'cook-d9323.firebaseapp.com',
    storageBucket: 'cook-d9323.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhN44RpUrrhNJXaDMTo5L5vx2uFrvYupw',
    appId: '1:944689820051:android:83506228bde4a91822f866',
    messagingSenderId: '944689820051',
    projectId: 'cook-d9323',
    storageBucket: 'cook-d9323.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLurZxUnxJa9YE7hkIq4k9IuMEOXQvsXs',
    appId: '1:944689820051:ios:d0054634a786803a22f866',
    messagingSenderId: '944689820051',
    projectId: 'cook-d9323',
    storageBucket: 'cook-d9323.appspot.com',
    iosBundleId: 'com.example.fcook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLurZxUnxJa9YE7hkIq4k9IuMEOXQvsXs',
    appId: '1:944689820051:ios:d0054634a786803a22f866',
    messagingSenderId: '944689820051',
    projectId: 'cook-d9323',
    storageBucket: 'cook-d9323.appspot.com',
    iosBundleId: 'com.example.fcook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_Tyok2vPh4qjXAnAnIzEkRCNHiiy6kiQ',
    appId: '1:944689820051:web:7bf8b1b8f001e09a22f866',
    messagingSenderId: '944689820051',
    projectId: 'cook-d9323',
    authDomain: 'cook-d9323.firebaseapp.com',
    storageBucket: 'cook-d9323.appspot.com',
  );
}
